# Generated by Django 5.1.3 on 2024-11-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_cart_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchesuploads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
