# Generated by Django 5.1.3 on 2024-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_watchesuploads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchesuploads',
            name='image',
            field=models.ImageField(upload_to='watches_images/'),
        ),
    ]
