# Generated by Django 5.1.3 on 2024-12-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_watchesuploads_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchreview',
            old_name='ratinf',
            new_name='rating',
        ),
    ]
